#pragma once

#include "NativeGameplayTags.h"

// 角色属性 ID 根标签。
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute);

// 角色设定属性 ID 标签。
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Setting);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Setting_Race);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Setting_Camp);

// 按属性分类组织的角色属性 ID 标签。
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Basic);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Basic_Strength);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Basic_Wisdom);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Basic_Agility);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Basic_Constitution);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource_Health);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource_Mana);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource_Stamina);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource_Shield);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Judgement);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Judgement_CriticalChance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Percentage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Percentage_CriticalDamage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Percentage_BlockDamageReduction);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Numeric);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Numeric_CarryWeight);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Numeric_Luck);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Numeric_Armor);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Numeric_AttackPower);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Numeric_AttackSpeed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Element);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Element_FireAffinity);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Element_WaterAffinity);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Element_ElectricAffinity);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Faith);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Faith_LightGod);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Faith_Nature);
