#pragma once

#include "NativeGameplayTags.h"

// 本文件集中声明角色属性与词条标签，统一维护两个系统共享的配置边界。

// 角色属性业务标签。
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Setting);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Setting_Race);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Ability);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Ability_Strength);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Ability_Wisdom);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Ability_Agility);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Ability_Constitution);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource_Health);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource_Mana);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource_Stamina);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Resource_Shield);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Judgement);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Judgement_CriticalChance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Combat);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Combat_CriticalDamage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Combat_BlockDamageReduction);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Combat_Armor);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Combat_AttackPower);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Combat_AttackSpeed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Action);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Action_MovementSpeedBonus);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Action_CarryWeight);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Action_BaseMovementSpeed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Loot);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Loot_Luck);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Element);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Element_FireAffinity);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Element_WaterAffinity);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Element_ElectricAffinity);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Faith);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Faith_LightGod);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Attribute_Faith_Nature);

// 词条逻辑标签。
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Entry);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Entry_ScalarModifier);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Entry_ResourceRecovery);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Entry_StateModifier);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Entry_CreateBuff);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Entry_MultiTarget);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(LxTag_Entry_DisplayText);
