;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="物品.装备.武器.村里最好的剑",NewTagName="物品.装备.武器.剑.单手剑.村里最好的剑")
+GameplayTagRedirects=(OldTagName="物品.buff.回复效果.生命回复效果",NewTagName="物品.buff.回复效果.生命回复")
+GameplayTagList=(Tag="交互内容可视化.交互提示",DevComment="")
+GameplayTagList=(Tag="交互内容可视化.交互提示.测试内容.NPC对话",DevComment="")
+GameplayTagList=(Tag="交互内容可视化.交互提示.测试内容.上锁",DevComment="")
+GameplayTagList=(Tag="交互内容可视化.交互提示.测试内容.关门",DevComment="")
+GameplayTagList=(Tag="交互内容可视化.交互提示.测试内容.关门选项NPC对话",DevComment="")
+GameplayTagList=(Tag="交互内容可视化.交互提示.测试内容.开门",DevComment="")
+GameplayTagList=(Tag="交互行为",DevComment="")
+GameplayTagList=(Tag="交互行为.NPC发言",DevComment="")
+GameplayTagList=(Tag="交互行为.NPC发言.告别",DevComment="")
+GameplayTagList=(Tag="交互行为.交易",DevComment="")
+GameplayTagList=(Tag="交互行为.交易.打开商店",DevComment="")
+GameplayTagList=(Tag="交互行为.仓库",DevComment="")
+GameplayTagList=(Tag="交互行为.仓库.打开仓库",DevComment="")
+GameplayTagList=(Tag="交互行为.入口",DevComment="")
+GameplayTagList=(Tag="交互行为.入口.与商人对话",DevComment="")
+GameplayTagList=(Tag="交互行为.宝箱",DevComment="")
+GameplayTagList=(Tag="交互行为.宝箱.打开宝箱",DevComment="")
+GameplayTagList=(Tag="交互行为.对话",DevComment="")
+GameplayTagList=(Tag="交互行为.对话.再见",DevComment="")
+GameplayTagList=(Tag="交互行为.对话.好的",DevComment="")
+GameplayTagList=(Tag="交互行为.物品交互.拾取物品",DevComment="")
+GameplayTagList=(Tag="交互行为.物品交互.拾取物品.拾取生命药剂",DevComment="")
+GameplayTagList=(Tag="交互行为.物品交互.玩家失去物品",DevComment="")
+GameplayTagList=(Tag="交互行为.物品交互.玩家得到物品",DevComment="")
+GameplayTagList=(Tag="单位命名.木桩",DevComment="")
+GameplayTagList=(Tag="单位命名.测试角色",DevComment="")
+GameplayTagList=(Tag="技能",DevComment="")
+GameplayTagList=(Tag="技能.法术技能",DevComment="")
+GameplayTagList=(Tag="技能.法术技能.光环",DevComment="")
+GameplayTagList=(Tag="技能.法术技能.光环.测试光环",DevComment="")
+GameplayTagList=(Tag="技能.法术技能.单次射线",DevComment="")
+GameplayTagList=(Tag="技能.法术技能.射线",DevComment="")
+GameplayTagList=(Tag="技能.法术技能.火球术",DevComment="")
+GameplayTagList=(Tag="文本样式",DevComment="")
+GameplayTagList=(Tag="文本样式.稀有度样式",DevComment="")
+GameplayTagList=(Tag="文本样式.稀有度样式.传说",DevComment="")
+GameplayTagList=(Tag="文本样式.稀有度样式.史诗",DevComment="")
+GameplayTagList=(Tag="文本样式.稀有度样式.普通",DevComment="")
+GameplayTagList=(Tag="文本样式.稀有度样式.神话",DevComment="")
+GameplayTagList=(Tag="文本样式.稀有度样式.稀有",DevComment="")
+GameplayTagList=(Tag="文本样式.稀有度样式.高级",DevComment="")
+GameplayTagList=(Tag="文本样式.聊天发言样式",DevComment="")
+GameplayTagList=(Tag="文本样式.聊天发言样式.玩家发言",DevComment="")
+GameplayTagList=(Tag="文本样式.聊天发言样式.系统发言",DevComment="")
+GameplayTagList=(Tag="文本样式.聊天发言样式.调试信息",DevComment="")
+GameplayTagList=(Tag="文本样式.词条样式",DevComment="")
+GameplayTagList=(Tag="文本样式.词条样式.传说词条",DevComment="")
+GameplayTagList=(Tag="文本样式.词条样式.史诗词条",DevComment="")
+GameplayTagList=(Tag="文本样式.词条样式.普通词条",DevComment="")
+GameplayTagList=(Tag="文本样式.词条样式.神话词条",DevComment="")
+GameplayTagList=(Tag="文本样式.词条样式.稀有词条",DevComment="")
+GameplayTagList=(Tag="文本样式.词条样式.高级词条",DevComment="")
+GameplayTagList=(Tag="物品.buff.回复效果",DevComment="")
+GameplayTagList=(Tag="物品.buff.回复效果.生命回复",DevComment="")
+GameplayTagList=(Tag="物品.buff.属性提升效果",DevComment="")
+GameplayTagList=(Tag="物品.buff.属性提升效果.力量增加",DevComment="")
+GameplayTagList=(Tag="物品.技能.光环",DevComment="")
+GameplayTagList=(Tag="物品.技能.光环.测试光环",DevComment="")
+GameplayTagList=(Tag="物品.技能.复合类型",DevComment="")
+GameplayTagList=(Tag="物品.技能.复合类型.测试复合技能",DevComment="")
+GameplayTagList=(Tag="物品.技能.射线",DevComment="")
+GameplayTagList=(Tag="物品.技能.射线.测试单次射线",DevComment="")
+GameplayTagList=(Tag="物品.技能.射线.测试射线",DevComment="")
+GameplayTagList=(Tag="物品.技能.投射物",DevComment="")
+GameplayTagList=(Tag="物品.技能.投射物.火球术",DevComment="")
+GameplayTagList=(Tag="物品.材料.货币.金币",DevComment="金币")
+GameplayTagList=(Tag="物品.消耗品.药剂.生命药剂.村里最好的生命药剂",DevComment="村里最好的生命药剂")
+GameplayTagList=(Tag="物品.消耗品.药剂.魔力药剂",DevComment="")
+GameplayTagList=(Tag="物品.消耗品.药剂.魔力药剂.村里最好的魔力药剂",DevComment="")
+GameplayTagList=(Tag="物品.装备.副手.水晶球.村里最好的水晶球",DevComment="村里最好的水晶球")
+GameplayTagList=(Tag="物品.装备.头盔.村里最好的头盔",DevComment="村里最好的头盔")
+GameplayTagList=(Tag="物品.装备.武器.剑.单手剑",DevComment="单手剑种类")
+GameplayTagList=(Tag="物品.装备.武器.剑.单手剑.村里最好的剑",DevComment="村里最好的剑")
+GameplayTagList=(Tag="物品.装备.武器.法杖.单手法杖.村里最好的法杖",DevComment="村里最好的法杖")
+GameplayTagList=(Tag="物品.装备.背包扩展",DevComment="")
+GameplayTagList=(Tag="物品.装备.饰品.戒指.村里最好的戒指",DevComment="村里最好的戒指")
+GameplayTagList=(Tag="职业.战斗.战士.见习战士",DevComment="")
+GameplayTagList=(Tag="职业.战斗.魔法师.见习魔法师",DevComment="")
+GameplayTagList=(Tag="通用效果.伤害效果.火焰伤害",DevComment="")
+GameplayTagList=(Tag="阵营",DevComment="")
+GameplayTagList=(Tag="阵营.种类.市民",DevComment="")
+GameplayTagList=(Tag="阵营.种类.怪物",DevComment="")

